# Data Science Project 1
Vasanth Rajasekaran and Sam Childs

## Collaboration Plan

We have created a private github repo to push and pull code that we write. We also have frequent calls to check in on our progress and help eachother out if there are any blockers

## Part 1 - Scraping

### Step One

In [1]:
!pip install lxml

Collecting lxml
  Downloading lxml-4.5.2-cp38-cp38-manylinux1_x86_64.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 903 kB/s eta 0:00:01     |█████████████▌                  | 2.3 MB 903 kB/s eta 0:00:04     |██████████████████████████      | 4.4 MB 903 kB/s eta 0:00:02
Installing collected packages: lxml
Successfully installed lxml-4.5.2

In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json 
import lxml
url = 'https://www.spaceweatherlive.com/en/solar-activity/top-50-solar-flares' # sets URL for easy use
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
# sets headers to mock an actual user^
response = requests.get(url, headers=headers) # sends get request to spaceweather and collects response
content = response.content # sets the content of the response

In [15]:
a = BeautifulSoup(content) # create a beautifulsoup object for the content 
a.prettify() # prettify it 
solarTable = a.find('table') # finds the table on the website 
dfSolar = pd.read_html(solarTable.prettify()) # converts html table into pandas df
dfSolar=dfSolar[0] 
dfSolar.columns = ['rank','x_class', 'date', 'region' ,'start_time', 'max_time', 'end_time', 'movie'] # sets columns
dfSolar

,rank,x_class,date,region,start_time,max_time,end_time,movie
0,1,X28+,2003/11/04,486,19:29,19:53,20:06,Movie View archive
1,2,X20+,2001/04/02,9393,21:32,21:51,22:03,Movie View archive
2,3,X17.2+,2003/10/28,486,09:51,11:10,11:24,Movie View archive
3,4,X17+,2005/09/07,808,17:17,17:40,18:03,Movie View archive
4,5,X14.4,2001/04/15,9415,13:19,13:50,13:55,Movie View archive
5,6,X10,2003/10/29,486,20:37,20:49,21:01,Movie View archive
6,7,X9.4,1997/11/06,8100,11:49,11:55,12:01,Movie View archive
7,8,X9.3,2017/09/06,2673,11:53,12:02,12:10,Movie View archive
8,9,X9,2006/12/05,930,10:18,10:35,10:45,Movie View archive
9,10,X8.3,2003/11/02,486,17:03,17:25,17:39,Movie View archive
10,11,X8.2,2017/09/10,2673,15:35,16:06,16:31,Movie View archive
11,12,X7.1,2005/01/20,720,06:36,07:01,07:26,Movie View archive
12,13,X6.9,2011/08/09,1263,07:48,08:05,08:08,Movie View archive
13,14,X6.5,2006/12/06,930,18:29,18:47,19:00,Movie View archive
14,15,X6.2,2005/09/09,808,19:13,20:04,20:36,Movie View archive
15,16,X6.2,2001/12/13,9733,14:20,14:30,14:35,Movie View archive
16,17,X5.7,2000/07/14,9077,10:03,10:24,10:43,Movie View archive
17,18,X5.6,2001/04/06,9415,19:10,19:21,19:31,Movie View archive
18,19,X5.4,2012/03/07,1429,00:02,00:24,00:40,Movie View archive
19,20,X5.4,2005/09/08,808,20:52,21:06,21:17,Movie View archive
20,21,X5.4,2003/10/23,486,08:19,08:35,08:49,Movie View archive
21,22,X5.3,2001/08/25,9591,16:23,16:45,17:04,Movie View archive
22,23,X4.9,2014/02/25,1990,00:39,00:49,01:03,Movie View archive
23,24,X4.9,1998/08/18,8307,22:10,22:19,22:28,View archive
24,25,X4.8,2002/07/23,39,00:18,00:35,00:47,Movie View archive
25,26,X4,2000/11/26,9236,16:34,16:48,16:56,Movie View archive
26,27,X3.9,2003/11/03,488,09:43,09:55,10:19,Movie View archive
27,28,X3.9,1998/08/19,8307,21:35,21:45,21:50,View archive
28,29,X3.8,2005/01/17,720,06:59,09:52,10:07,Movie View archive
29,30,X3.7,1998/11/22,8384,06:30,06:42,06:49,Movie View archive
30,31,X3.6,2005/09/09,808,09:42,09:59,10:08,Movie View archive
31,32,X3.6,2004/07/16,649,13:49,13:55,14:01,Movie View archive
32,33,X3.6,2003/05/28,365,00:17,00:27,00:39,Movie View archive
33,34,X3.4,2006/12/13,930,02:14,02:40,02:57,Movie View archive
34,35,X3.4,2001/12/28,9767,20:02,20:45,21:32,Movie View archive
35,36,X3.3,2013/11/05,1890,22:07,22:12,22:15,Movie View archive
36,37,X3.3,2002/07/20,39,21:04,21:30,21:54,Movie View archive
37,38,X3.3,1998/11/28,8395,04:54,05:52,06:13,Movie View archive
38,39,X3.2,2013/05/14,1748,00:00,01:11,01:20,Movie View archive
39,40,X3.1,2014/10/24,2192,21:07,21:41,22:13,Movie View archive
40,41,X3.1,2002/08/24,69,00:49,01:12,01:31,Movie View archive
41,42,X3,2002/07/15,30,19:59,20:08,20:14,Movie View archive
42,43,X2.8,2013/05/13,1748,15:48,16:05,16:16,Movie View archive
43,44,X2.8,2001/12/11,9733,07:58,08:08,08:14,Movie View archive
44,45,X2.8,1998/08/18,8307,08:14,08:24,08:32,View archive
45,46,X2.7,2015/05/05,2339,22:05,22:11,22:15,Movie View archive
46,47,X2.7,2003/11/03,488,01:09,01:30,01:45,Movie View archive
47,48,X2.7,1998/05/06,8210,07:58,08:09,08:20,Movie View archive
48,49,X2.6,2005/01/15,720,22:25,23:02,23:31,Movie View archive
49,50,X2.6,2001/09/24,9632,09:32,10:38,11:09,Movie View archive

### Step 2 - Tidy Flare Data

In [4]:
del dfSolar['movie'] # cuts 'movie' column

In [16]:
import datetime
iterr = dfSolar.iterrows() # sets up iterator for table
for i,row in iterr: # loops through rows
    
    temp = row['start_time'] + ' '+ row['date'] # create one string with both start time and date
    startDatetime = pd.to_datetime(temp) # convert string into a datetime object 
    dfSolar.loc[i,'start_time'] = startDatetime # uses current row index to replace time with datetime object 
    
    temp = row['max_time'] + ' '+ row['date'] # repeats replacement for all types of times
    maxDatetime = pd.to_datetime(temp)
    dfSolar.loc[i,'max_time'] = maxDatetime
    
    temp = row['end_time'] + ' '+ row['date']
    endDatetime = pd.to_datetime(temp)
    dfSolar.loc[i,'end_time'] = endDatetime

dfSolar = dfSolar.drop(columns=['date'], axis=1) # drops date column since no longer needed
dfSolar = dfSolar.rename(columns={"start_time": "start_datetime", "max_time": "max_datetime", "end_time": "end_datetime"}, errors="raise")
# renames columns ^
dfSolar = dfSolar[['rank','x_class','start_datetime','max_datetime','end_datetime','region']] # rearrange columns
dfSolar

,rank,x_class,start_datetime,max_datetime,end_datetime,region
0,1,X28+,2003-11-04 19:29:00,2003-11-04 19:53:00,2003-11-04 20:06:00,486
1,2,X20+,2001-04-02 21:32:00,2001-04-02 21:51:00,2001-04-02 22:03:00,9393
2,3,X17.2+,2003-10-28 09:51:00,2003-10-28 11:10:00,2003-10-28 11:24:00,486
3,4,X17+,2005-09-07 17:17:00,2005-09-07 17:40:00,2005-09-07 18:03:00,808
4,5,X14.4,2001-04-15 13:19:00,2001-04-15 13:50:00,2001-04-15 13:55:00,9415
5,6,X10,2003-10-29 20:37:00,2003-10-29 20:49:00,2003-10-29 21:01:00,486
6,7,X9.4,1997-11-06 11:49:00,1997-11-06 11:55:00,1997-11-06 12:01:00,8100
7,8,X9.3,2017-09-06 11:53:00,2017-09-06 12:02:00,2017-09-06 12:10:00,2673
8,9,X9,2006-12-05 10:18:00,2006-12-05 10:35:00,2006-12-05 10:45:00,930
9,10,X8.3,2003-11-02 17:03:00,2003-11-02 17:25:00,2003-11-02 17:39:00,486
10,11,X8.2,2017-09-10 15:35:00,2017-09-10 16:06:00,2017-09-10 16:31:00,2673
11,12,X7.1,2005-01-20 06:36:00,2005-01-20 07:01:00,2005-01-20 07:26:00,720
12,13,X6.9,2011-08-09 07:48:00,2011-08-09 08:05:00,2011-08-09 08:08:00,1263
13,14,X6.5,2006-12-06 18:29:00,2006-12-06 18:47:00,2006-12-06 19:00:00,930
14,15,X6.2,2005-09-09 19:13:00,2005-09-09 20:04:00,2005-09-09 20:36:00,808
15,16,X6.2,2001-12-13 14:20:00,2001-12-13 14:30:00,2001-12-13 14:35:00,9733
16,17,X5.7,2000-07-14 10:03:00,2000-07-14 10:24:00,2000-07-14 10:43:00,9077
17,18,X5.6,2001-04-06 19:10:00,2001-04-06 19:21:00,2001-04-06 19:31:00,9415
18,19,X5.4,2012-03-07 00:02:00,2012-03-07 00:24:00,2012-03-07 00:40:00,1429
19,20,X5.4,2005-09-08 20:52:00,2005-09-08 21:06:00,2005-09-08 21:17:00,808
20,21,X5.4,2003-10-23 08:19:00,2003-10-23 08:35:00,2003-10-23 08:49:00,486
21,22,X5.3,2001-08-25 16:23:00,2001-08-25 16:45:00,2001-08-25 17:04:00,9591
22,23,X4.9,2014-02-25 00:39:00,2014-02-25 00:49:00,2014-02-25 01:03:00,1990
23,24,X4.9,1998-08-18 22:10:00,1998-08-18 22:19:00,1998-08-18 22:28:00,8307
24,25,X4.8,2002-07-23 00:18:00,2002-07-23 00:35:00,2002-07-23 00:47:00,39
25,26,X4,2000-11-26 16:34:00,2000-11-26 16:48:00,2000-11-26 16:56:00,9236
26,27,X3.9,2003-11-03 09:43:00,2003-11-03 09:55:00,2003-11-03 10:19:00,488
27,28,X3.9,1998-08-19 21:35:00,1998-08-19 21:45:00,1998-08-19 21:50:00,8307
28,29,X3.8,2005-01-17 06:59:00,2005-01-17 09:52:00,2005-01-17 10:07:00,720
29,30,X3.7,1998-11-22 06:30:00,1998-11-22 06:42:00,1998-11-22 06:49:00,8384
30,31,X3.6,2005-09-09 09:42:00,2005-09-09 09:59:00,2005-09-09 10:08:00,808
31,32,X3.6,2004-07-16 13:49:00,2004-07-16 13:55:00,2004-07-16 14:01:00,649
32,33,X3.6,2003-05-28 00:17:00,2003-05-28 00:27:00,2003-05-28 00:39:00,365
33,34,X3.4,2006-12-13 02:14:00,2006-12-13 02:40:00,2006-12-13 02:57:00,930
34,35,X3.4,2001-12-28 20:02:00,2001-12-28 20:45:00,2001-12-28 21:32:00,9767
35,36,X3.3,2013-11-05 22:07:00,2013-11-05 22:12:00,2013-11-05 22:15:00,1890
36,37,X3.3,2002-07-20 21:04:00,2002-07-20 21:30:00,2002-07-20 21:54:00,39
37,38,X3.3,1998-11-28 04:54:00,1998-11-28 05:52:00,1998-11-28 06:13:00,8395
38,39,X3.2,2013-05-14 00:00:00,2013-05-14 01:11:00,2013-05-14 01:20:00,1748
39,40,X3.1,2014-10-24 21:07:00,2014-10-24 21:41:00,2014-10-24 22:13:00,2192
40,41,X3.1,2002-08-24 00:49:00,2002-08-24 01:12:00,2002-08-24 01:31:00,69
41,42,X3,2002-07-15 19:59:00,2002-07-15 20:08:00,2002-07-15 20:14:00,30
42,43,X2.8,2013-05-13 15:48:00,2013-05-13 16:05:00,2013-05-13 16:16:00,1748
43,44,X2.8,2001-12-11 07:58:00,2001-12-11 08:08:00,2001-12-11 08:14:00,9733
44,45,X2.8,1998-08-18 08:14:00,1998-08-18 08:24:00,1998-08-18 08:32:00,8307
45,46,X2.7,2015-05-05 22:05:00,2015-05-05 22:11:00,2015-05-05 22:15:00,2339
46,47,X2.7,2003-11-03 01:09:00,2003-11-03 01:30:00,2003-11-03 01:45:00,488
47,48,X2.7,1998-05-06 07:58:00,1998-05-06 08:09:00,1998-05-06 08:20:00,8210
48,49,X2.6,2005-01-15 22:25:00,2005-01-15 23:02:00,2005-01-15 23:31:00,720
49,50,X2.6,2001-09-24 09:32:00,2001-09-24 10:38:00,2001-09-24 11:09:00,9632

In [17]:
dfSolar.info() # displays dtypes of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rank            50 non-null     int64
 1   x_class         50 non-null     object
 2   start_datetime  50 non-null     object
 3   max_datetime    50 non-null     object
 4   end_datetime    50 non-null     object
 5   region          50 non-null     int64
dtypes: int64(2), object(4)
memory usage: 2.5+ KB

### Step 3 - Scrape Nasa Data

In [83]:
import re
import numpy as np
url2 = 'https://cdaw.gsfc.nasa.gov/CME_list/radio/waves_type2.html'
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
response2 = requests.get(url2, headers=headers)
content2 = response2.content

In [84]:
b = BeautifulSoup(content2, "html.parser")
s = str(b.pre).split('\n')[12:-2]
data = {"Start Date": [],
        "Start Time": [],
        "End Date": [],
        "End Time": [],
        "Max Frequency": [],
        "Min Frequency": [],
        "Flare Location": [],
        "NOAA": [],
        "Imp": [],
        "CME Date": [],
        "CME Time": [],
        "CPA": [],
        "Width": [],
        "Speed": []}
        
dfNasa = pd.DataFrame(data)

In [85]:
for i in s:
    row = i.split(' ')
    a = [x for x in row if x]
    b = [y for y in a if y!='<a']
    temp = re.sub(r'href[^<]+>', '', b[4])
    noLinkMax = re.sub(r'</a>','', temp)
    noLinkMax = re.sub(r'</a>','', temp)
    if noLinkMax != '????':
        noLinkMax = int(noLinkMax)
    else:
        noLinkMax = np.nan
        
    
    temp = re.sub(r'href[^<]+>', '', b[5])
    noLinkMin = re.sub(r'</a>','', temp)
    if noLinkMin != '????':
        noLinkMin = int(noLinkMin)
    else:
        noLinkMin = np.nan
    
    tempCME = re.sub(r'href[^<]+>', '', b[9])
    noLinkCME = re.sub(r'</a>','', tempCME)
    
    tempSpeed = re.sub(r'href[^<]+>', '', b[13])
    noLinkSpeed = re.sub(r'</a>','', tempSpeed)
    
    imp = b[8]
    if imp[-1] == '.':
        imp = imp[:-1] + '+'
        
    year = b[0][0:4]
    enddate = year + '/'+ b[2]
    
    cmeDate = year + '/' + noLinkCME
    
    insertRow = pd.Series({"Start Date": b[0],
                       "Start Time": b[1],
                       "End Date": enddate,
                       "End Time": b[3],
                       "Max Frequency": noLinkMax,
                       "Min Frequency": noLinkMin,
                       "Flare Location": b[6],
                       "NOAA": b[7],
                       "Imp": imp,
                       "CME Date": cmeDate,
                       "CME Time": b[10],
                       "CPA": b[11],
                       "Width": b[12],
                       "Speed": noLinkSpeed
                      })
    dfNasa = dfNasa.append(insertRow, ignore_index=True)
dfNasa

,Start Date,Start Time,End Date,End Time,Max Frequency,Min Frequency,Flare Location,NOAA,Imp,CME Date,CME Time,CPA,Width,Speed
0,1997/04/01,14:00,1997/04/01,14:15,8000.0,4000.0,S25E16,8026,M1.3,1997/04/01,15:18,74,79,312
1,1997/04/07,14:30,1997/04/07,17:30,11000.0,1000.0,S28E19,8027,C6.8,1997/04/07,14:27,Halo,360,878
2,1997/05/12,05:15,1997/05/14,16:00,12000.0,80.0,N21W08,8038,C1.3,1997/05/12,05:30,Halo,360,464
3,1997/05/21,20:20,1997/05/21,22:00,5000.0,500.0,N05W12,8040,M1.3,1997/05/21,21:00,263,165,296
4,1997/09/23,21:53,1997/09/23,22:16,6000.0,2000.0,S29E25,8088,C1.4,1997/09/23,22:02,133,155,712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,2017/09/04,20:27,2017/09/05,04:54,14000.0,210.0,S10W12,12673,M5.5,2017/09/04,20:12,Halo,360,1418
514,2017/09/06,12:05,2017/09/07,08:00,16000.0,70.0,S08W33,12673,X9.3,2017/09/06,12:24,Halo,360,1571
515,2017/09/10,16:02,2017/09/11,06:50,16000.0,150.0,S09W92,-----,X8.3,2017/09/10,16:00,Halo,360,3163
516,2017/09/12,07:38,2017/09/12,07:43,16000.0,13000.0,N08E48,12680,C3.0,2017/09/12,08:03,124,96,252
517,2017/09/17,11:45,2017/09/17,12:35,16000.0,900.0,S08E170,-----,----,2017/09/17,12:00,Halo,360,1385

### Step 4 - Tidy Nasa Data

In [86]:
dfNasa["Flare Location"] = dfNasa["Flare Location"].replace("Back","BACK")
dfNasa["Flare Location"] = dfNasa["Flare Location"].replace("Back?","BACK")

dfNasa["NOAA"] = dfNasa["NOAA"].replace("-----",np.NaN)
dfNasa["NOAA"] = dfNasa["NOAA"].replace("DSF","FILA")
dfNasa["Imp"] = dfNasa["Imp"].replace("----",np.NaN)

dfNasa['CME Time'] = dfNasa['CME Time'].replace('--:--','00:00')

dfNasa["CME Date"] = dfNasa["CME Date"].replace("----",np.NaN)
dfNasa["CME Date"] = dfNasa["CME Date"].replace("----",np.NaN)
dfNasa["CPA"] = dfNasa["CPA"].replace("----",np.NaN)
dfNasa["Is Flare"] = [True if row == "Halo" else False for row in dfNasa['CPA']]
dfNasa["CPA"] = dfNasa["CPA"].replace("Halo",np.NaN)
dfNasa["Width"] = dfNasa["Width"].replace("----",np.NaN)
dfNasa["Speed"] = dfNasa["Speed"].replace("----",np.NaN)
dfNasa["Width Lower Bound"] = [True if "&gt;" in str(row) else False for row in dfNasa['Width']]
dfNasa["Width"] = [int(str(row)[4:]) if "&gt;" in str(row) else row for row in dfNasa['Width']]
dfNasa["End Time"] = dfNasa["End Time"].replace("24:00","23:59")
dfNasa["Start DateTime"] = pd.to_datetime(dfNasa["Start Date"] + " " + dfNasa["Start Time"])
dfNasa["End DateTime"] = pd.to_datetime(dfNasa["End Date"] + " " + dfNasa["End Time"])
dfNasa["CME DateTime"] = pd.to_datetime(dfNasa["CME Date"] + " " + dfNasa["CME Time"])

# Reorder table
"""
dfNasa = dfNasa[['Start DateTime', 'End DateTime',
                "Max Frequency", "Min Frequency",
                "Flare Location", "NOAA","Imp",
                "CME DateTime", "CPA", "Width",
                "Speed","Is Halo","Width Lower Bound"]] 
"""


dfNasa = dfNasa.drop(["Start Date", "Start Time", "End Date", "End Time", "CME Date", "CME Time"], axis = 1)
# And don't forget to check each column for the correct datatype
dfNasa.info()
dfNasa

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Max Frequency      514 non-null    float64
 1   Min Frequency      514 non-null    float64
 2   Flare Location     518 non-null    object
 3   NOAA               424 non-null    object
 4   Imp                404 non-null    object
 5   CPA                210 non-null    object
 6   Width              502 non-null    object
 7   Speed              496 non-null    object
 8   Is Flare           518 non-null    bool
 9   Width Lower Bound  518 non-null    bool
 10  Start DateTime     518 non-null    datetime64[ns]
 11  End DateTime       518 non-null    datetime64[ns]
 12  CME DateTime       518 non-null    datetime64[ns]
dtypes: bool(2), datetime64[ns](3), float64(2), object(6)
memory usage: 45.7+ KB

,Max Frequency,Min Frequency,Flare Location,NOAA,Imp,CPA,Width,Speed,Is Flare,Width Lower Bound,Start DateTime,End DateTime,CME DateTime
0,8000.0,4000.0,S25E16,8026,M1.3,74,79,312,False,False,1997-04-01 14:00:00,1997-04-01 14:15:00,1997-04-01 15:18:00
1,11000.0,1000.0,S28E19,8027,C6.8,NaN,360,878,True,False,1997-04-07 14:30:00,1997-04-07 17:30:00,1997-04-07 14:27:00
2,12000.0,80.0,N21W08,8038,C1.3,NaN,360,464,True,False,1997-05-12 05:15:00,1997-05-14 16:00:00,1997-05-12 05:30:00
3,5000.0,500.0,N05W12,8040,M1.3,263,165,296,False,False,1997-05-21 20:20:00,1997-05-21 22:00:00,1997-05-21 21:00:00
4,6000.0,2000.0,S29E25,8088,C1.4,133,155,712,False,False,1997-09-23 21:53:00,1997-09-23 22:16:00,1997-09-23 22:02:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,14000.0,210.0,S10W12,12673,M5.5,NaN,360,1418,True,False,2017-09-04 20:27:00,2017-09-05 04:54:00,2017-09-04 20:12:00
514,16000.0,70.0,S08W33,12673,X9.3,NaN,360,1571,True,False,2017-09-06 12:05:00,2017-09-07 08:00:00,2017-09-06 12:24:00
515,16000.0,150.0,S09W92,NaN,X8.3,NaN,360,3163,True,False,2017-09-10 16:02:00,2017-09-11 06:50:00,2017-09-10 16:00:00
516,16000.0,13000.0,N08E48,12680,C3.0,124,96,252,False,False,2017-09-12 07:38:00,2017-09-12 07:43:00,2017-09-12 08:03:00
517,16000.0,900.0,S08E170,NaN,NaN,NaN,360,1385,True,False,2017-09-17 11:45:00,2017-09-17 12:35:00,2017-09-17 12:00:00

## Part 2 - Analysis

### Question 1: Replication

The Nasa Data can replicate the SpaceWeather Table fairly well. It is missing a few values that have the same Imp values as other flare events. They are missing from the raw data on NASA's website, and it's hard to say whether the cause is a clerical error or some systemic error in the NASA data processing pipeline. Regardless, the result is that our replicated table includes some instances with Imp values that are lower than the min of the SpaceWeather Table.

In [88]:
dfReplicate = dfNasa
dfReplicate["Imp Rank"] = [float(str(row[1:-1])) if "X" in str(row) else np.nan for row in dfReplicate["Imp"]]
dfRank = dfReplicate.sort_values(by="Imp Rank", ascending = False)
dfRank.head(50)

,Max Frequency,Min Frequency,Flare Location,NOAA,Imp,CPA,Width,Speed,Is Flare,Width Lower Bound,Start DateTime,End DateTime,CME DateTime,Imp Rank
240,10000.0,200.0,S19W83,10486,X28+,NaN,360,2657,True,False,2003-11-04 20:00:00,2003-11-04 23:59:00,2003-11-04 19:54:00,28.0
117,14000.0,250.0,N19W72,9393,X20+,261,244,2505,False,False,2001-04-02 22:05:00,2001-04-03 02:30:00,2001-04-02 22:06:00,20.0
233,14000.0,40.0,S16E08,10486,X17+,NaN,360,2459,True,False,2003-10-28 11:10:00,2003-10-29 23:59:00,2003-10-28 11:30:00,17.0
126,14000.0,40.0,S20W85,9415,X14+,245,167,1199,False,False,2001-04-15 14:05:00,2001-04-16 13:00:00,2001-04-15 14:06:00,14.0
234,11000.0,500.0,S15W02,10486,X10+,NaN,360,2029,True,False,2003-10-29 20:55:00,2003-10-29 23:59:00,2003-10-29 20:54:00,10.0
514,16000.0,70.0,S08W33,12673,X9.3,NaN,360,1571,True,False,2017-09-06 12:05:00,2017-09-07 08:00:00,2017-09-06 12:24:00,9.0
328,14000.0,250.0,S07E68,10930,X9.0,NaN,NaN,NaN,False,False,2006-12-05 10:50:00,2006-12-05 20:00:00,2006-01-01 00:00:00,9.0
8,14000.0,100.0,S18W63,8100,X9.4,NaN,360,1556,True,False,1997-11-06 12:20:00,1997-11-07 08:30:00,1997-11-06 12:10:00,9.0
237,12000.0,250.0,S14W56,10486,X8.3,NaN,360,2598,True,False,2003-11-02 17:30:00,2003-11-03 01:00:00,2003-11-02 17:30:00,8.0
515,16000.0,150.0,S09W92,NaN,X8.3,NaN,360,3163,True,False,2017-09-10 16:02:00,2017-09-11 06:50:00,2017-09-10 16:00:00,8.0
288,14000.0,25.0,N14W61,10720,X7.1,NaN,360,882,True,False,2005-01-20 07:15:00,2005-01-20 16:30:00,2005-01-20 06:54:00,7.0
317,10000.0,50.0,S12E67,10808,X6.2,NaN,360,2257,True,False,2005-09-09 19:45:00,2005-09-09 22:00:00,2005-09-09 19:48:00,6.0
331,16000.0,30.0,S05E64,10930,X6.5,NaN,NaN,NaN,False,False,2006-12-06 19:00:00,2006-12-08 23:59:00,2006-01-01 00:00:00,6.0
359,16000.0,4000.0,N17W69,11263,X6.9,NaN,360,1610,True,False,2011-08-09 08:20:00,2011-08-09 08:35:00,2011-08-09 08:12:00,6.0
135,8000.0,170.0,S17E34,9591,X5.3,NaN,360,1433,True,False,2001-08-25 16:50:00,2001-08-25 23:00:00,2001-08-25 16:50:00,5.0
82,14000.0,80.0,N22W07,9077,X5.7,NaN,360,1674,True,False,2000-07-14 10:30:00,2000-07-15 14:30:00,2000-07-14 10:54:00,5.0
375,16000.0,30.0,N17E27,11429,X5.4,NaN,360,2684,True,False,2012-03-07 01:00:00,2012-03-08 19:00:00,2012-03-07 00:24:00,5.0
121,14000.0,230.0,S21E31,9415,X5.6,NaN,360,1270,True,False,2001-04-06 19:35:00,2001-04-07 01:50:00,2001-04-06 19:30:00,5.0
193,11000.0,400.0,S13E72,10039,X4.8,NaN,360,2285,True,False,2002-07-23 00:50:00,2002-07-23 04:00:00,2002-07-23 00:42:00,4.0
443,14000.0,100.0,S12E82,11990,X4.9,NaN,360,2147,True,False,2014-02-25 00:56:00,2014-02-25 11:28:00,2014-02-25 01:25:00,4.0
104,14000.0,7000.0,N18W38,9236,X4.0,NaN,360,980,True,False,2000-11-26 17:00:00,2000-11-26 17:15:00,2000-11-26 17:06:00,4.0
286,6100.0,1500.0,N15W25,10720,X3.8,NaN,360,2547,True,False,2005-01-17 10:00:00,2005-01-17 10:35:00,2005-01-17 09:54:00,3.0
192,10000.0,2000.0,S13E90,10039,X3.3,NaN,360,1941,True,False,2002-07-20 21:30:00,2002-07-20 22:20:00,2002-07-20 22:06:00,3.0
332,12000.0,150.0,S06W23,10930,X3.4,NaN,360,1774,True,False,2006-12-13 02:45:00,2006-12-13 10:40:00,2006-12-13 02:54:00,3.0
160,14000.0,350.0,S26E90,9756,X3.4,NaN,360,2216,True,False,2001-12-28 20:35:00,2001-12-29 03:00:00,2001-12-28 20:30:00,3.0
201,5000.0,400.0,S02W81,10069,X3.1,NaN,360,1913,True,False,2002-08-24 01:45:00,2002-08-24 03:25:00,2002-08-24 01:27:00,3.0
404,16000.0,240.0,N08E77,11748,X3.2,NaN,360,2625,True,False,2013-05-14 01:16:00,2013-05-14 08:20:00,2013-05-14 01:25:00,3.0
239,6000.0,400.0,N08W77,10488,X3.9,293,103,1420,False,False,2003-11-03 10:00:00,2003-11-03 12:30:00,2003-11-03 10:06:00,3.0
222,1000.0,200.0,S07W20,10365,X3.6,NaN,360,1366,True,False,2003-05-28 01:00:00,2003-05-29 00:30:00,2003-05-28 00:50:00,3.0
285,14000.0,30.0,N15W25,10720,X2.0,NaN,360,2094,True,False,2005-01-17 09:25:00,2005-01-17 16:00:00,2005-01-17 09:30:00,2.0
284,3000.0,40.0,N15W05,10720,X2.6,NaN,360,2861,True,False,2005-01-15 23:00:00,2005-01-17 00:00:00,2005-01-15 23:06:00,2.0
274,14000.0,60.0,N09W17,10696,X2.0,NaN,360,1759,True,False,2004-11-07 16:25:00,2004-11-08 20:00:00,2004-11-07 16:54:00,2.0
276,14000.0,1000.0,N09W49,10696,X2.5,NaN,360,3387,True,False,2004-11-10 02:25:00,2004-11-10 03:40:00,2004-11-10 02:26:00,2.0
73,14000.0,40.0,N20E18,9026,X2.3,NaN,360,1119,True,False,2000-06-06 15:20:00,2000-06-08 09:00:00,2000-06-06 15:54:00,2.0
318,14000.0,200.0,S13E47,10808,X2.1,NaN,360,1893,True,False,2005-09-10 21:45:00,2005-09-11 01:00:00,2005-09-10 21:52:00,2.0
19,14000.0,5000.0,S11W65,8210,X2.7,309,190,1099,False,False,1998-05-06 08:25:00,1998-05-06 08:35:00,1998-05-06 08:29:00,2.0
345,16000.0,400.0,S20W12,11158,X2.2,NaN,360,669,True,False,2011-02-15 02:10:00,2011-02-15 07:00:00,2011-02-15 02:24:00,2.0
361,16000.0,150.0,N14W18,11283,X2.1,NaN,360,575,True,False,2011-09-06 22:30:00,2011-09-07 15:40:00,2011-09-06 23:05:00,2.0
403,16000.0,300.0,N11E85,11748,X2.8,NaN,360,1850,True,False,2013-05-13 16:15:00,2013-05-13 19:10:00,2013-05-13 16:07:00,2.0
420,16000.0,200.0,S06E69,11882,X2.1,NaN,360,1081,True,False,2013-10-25 15:08:00,2013-10-25 22:32:00,2013-10-25 15:12:00,2.0
487,14000.0,500.0,N15E79,12339,X2.7,NaN,360,715,True,False,2015-05-05 22:24:00,2015-05-05 23:14:00,2015-05-05 22:24:00,2.0
9,14000.0,7000.0,N17E63,8113,X2.6,98,91,441,False,False,1997-11-27 13:30:00,1997-11-27 14:00:00,1997-11-27 13:56:00,2.0
238,3000.0,1500.0,N10W83,10488,X2.7,304,65,827,False,False,2003-11-03 01:15:00,2003-11-03 01:25:00,2003-11-03 01:59:00,2.0
7,14000.0,100.0,S14W33,8100,X2.1,NaN,360,785,True,False,1997-11-04 06:00:00,1997-11-05 04:30:00,1997-11-04 06:10:00,2.0
142,7000.0,30.0,S16E23,9632,X2.6,NaN,360,2402,True,False,2001-09-24 10:45:00,2001-09-25 20:00:00,2001-09-24 10:30:00,2.0
98,14000.0,100.0,N20W05,9236,X2.0,NaN,360,1289,True,False,2000-11-24 05:10:00,2000-11-24 15:00:00,2000-11-24 05:30:00,2.0
99,14000.0,200.0,N22W07,9236,X2.3,NaN,360,1245,True,False,2000-11-24 15:25:00,2000-11-24 22:00:00,2000-11-24 15:30:00,2.0
125,14000.0,7000.0,S19W43,9415,X2.0,NaN,360,1184,True,False,2001-04-12 10:20:00,2001-04-12 10:40:00,2001-04-12 10:31:00,2.0
123,14000.0,100.0,S23W09,9415,X2.3,NaN,360,2411,True,False,2001-04-10 05:24:00,2001-04-10 23:59:00,2001-04-10 05:30:00,2.0
402,16000.0,2000.0,N11E90,11748,X1.7,NaN,360,1270,True,False,2013-05-13 02:20:00,2013-05-13 03:00:00,2013-05-13 02:00:00,1.0

### Question 2: integration

In [98]:
from datetime import timedelta as td
solarIter = dfSolar.iterrows() # sets up iterator for table
for i,row in solarIter:
    samePower = dfNasa[dfNasa['Imp'] == row['x_class']]
    if len(samePower) > 0:
        matchIter = samePower.iterrows()
        for j,r in matchIter:
            timeD1 = row['max_datetime'] - row['start_datetime'] 
            timeD2 = r['CME DateTime']- r['Start DateTime']
            if (timeD1 > timeD2+td(hours=-5)) and (timeD1 < timeD2+td(hours=5)):
                dfNasa.loc[j, 'Solar Rank'] = row['rank']
                break
dfNasa = dfNasa.sort_values(by='Solar Rank', ascending = True)
dfNasa.head(50)

,Max Frequency,Min Frequency,Flare Location,NOAA,Imp,CPA,Width,Speed,Is Flare,Width Lower Bound,Start DateTime,End DateTime,CME DateTime,Imp Rank,Solar Rank
240,10000.0,200.0,S19W83,10486,X28+,NaN,360,2657,True,False,2003-11-04 20:00:00,2003-11-04 23:59:00,2003-11-04 19:54:00,28.0,1.0
117,14000.0,250.0,N19W72,9393,X20+,261,244,2505,False,False,2001-04-02 22:05:00,2001-04-03 02:30:00,2001-04-02 22:06:00,20.0,2.0
233,14000.0,40.0,S16E08,10486,X17+,NaN,360,2459,True,False,2003-10-28 11:10:00,2003-10-29 23:59:00,2003-10-28 11:30:00,17.0,4.0
8,14000.0,100.0,S18W63,8100,X9.4,NaN,360,1556,True,False,1997-11-06 12:20:00,1997-11-07 08:30:00,1997-11-06 12:10:00,9.0,7.0
514,16000.0,70.0,S08W33,12673,X9.3,NaN,360,1571,True,False,2017-09-06 12:05:00,2017-09-07 08:00:00,2017-09-06 12:24:00,9.0,8.0
237,12000.0,250.0,S14W56,10486,X8.3,NaN,360,2598,True,False,2003-11-02 17:30:00,2003-11-03 01:00:00,2003-11-02 17:30:00,8.0,10.0
288,14000.0,25.0,N14W61,10720,X7.1,NaN,360,882,True,False,2005-01-20 07:15:00,2005-01-20 16:30:00,2005-01-20 06:54:00,7.0,12.0
359,16000.0,4000.0,N17W69,11263,X6.9,NaN,360,1610,True,False,2011-08-09 08:20:00,2011-08-09 08:35:00,2011-08-09 08:12:00,6.0,13.0
317,10000.0,50.0,S12E67,10808,X6.2,NaN,360,2257,True,False,2005-09-09 19:45:00,2005-09-09 22:00:00,2005-09-09 19:48:00,6.0,16.0
82,14000.0,80.0,N22W07,9077,X5.7,NaN,360,1674,True,False,2000-07-14 10:30:00,2000-07-15 14:30:00,2000-07-14 10:54:00,5.0,17.0
121,14000.0,230.0,S21E31,9415,X5.6,NaN,360,1270,True,False,2001-04-06 19:35:00,2001-04-07 01:50:00,2001-04-06 19:30:00,5.0,18.0
375,16000.0,30.0,N17E27,11429,X5.4,NaN,360,2684,True,False,2012-03-07 01:00:00,2012-03-08 19:00:00,2012-03-07 00:24:00,5.0,21.0
135,8000.0,170.0,S17E34,9591,X5.3,NaN,360,1433,True,False,2001-08-25 16:50:00,2001-08-25 23:00:00,2001-08-25 16:50:00,5.0,22.0
443,14000.0,100.0,S12E82,11990,X4.9,NaN,360,2147,True,False,2014-02-25 00:56:00,2014-02-25 11:28:00,2014-02-25 01:25:00,4.0,24.0
193,11000.0,400.0,S13E72,10039,X4.8,NaN,360,2285,True,False,2002-07-23 00:50:00,2002-07-23 04:00:00,2002-07-23 00:42:00,4.0,25.0
239,6000.0,400.0,N08W77,10488,X3.9,293,103,1420,False,False,2003-11-03 10:00:00,2003-11-03 12:30:00,2003-11-03 10:06:00,3.0,28.0
286,6100.0,1500.0,N15W25,10720,X3.8,NaN,360,2547,True,False,2005-01-17 10:00:00,2005-01-17 10:35:00,2005-01-17 09:54:00,3.0,29.0
222,1000.0,200.0,S07W20,10365,X3.6,NaN,360,1366,True,False,2003-05-28 01:00:00,2003-05-29 00:30:00,2003-05-28 00:50:00,3.0,33.0
160,14000.0,350.0,S26E90,9756,X3.4,NaN,360,2216,True,False,2001-12-28 20:35:00,2001-12-29 03:00:00,2001-12-28 20:30:00,3.0,35.0
192,10000.0,2000.0,S13E90,10039,X3.3,NaN,360,1941,True,False,2002-07-20 21:30:00,2002-07-20 22:20:00,2002-07-20 22:06:00,3.0,38.0
404,16000.0,240.0,N08E77,11748,X3.2,NaN,360,2625,True,False,2013-05-14 01:16:00,2013-05-14 08:20:00,2013-05-14 01:25:00,3.0,39.0
201,5000.0,400.0,S02W81,10069,X3.1,NaN,360,1913,True,False,2002-08-24 01:45:00,2002-08-24 03:25:00,2002-08-24 01:27:00,3.0,41.0
403,16000.0,300.0,N11E85,11748,X2.8,NaN,360,1850,True,False,2013-05-13 16:15:00,2013-05-13 19:10:00,2013-05-13 16:07:00,2.0,45.0
19,14000.0,5000.0,S11W65,8210,X2.7,309,190,1099,False,False,1998-05-06 08:25:00,1998-05-06 08:35:00,1998-05-06 08:29:00,2.0,48.0
9,14000.0,7000.0,N17E63,8113,X2.6,98,91,441,False,False,1997-11-27 13:30:00,1997-11-27 14:00:00,1997-11-27 13:56:00,2.0,50.0
0,8000.0,4000.0,S25E16,8026,M1.3,74,79,312,False,False,1997-04-01 14:00:00,1997-04-01 14:15:00,1997-04-01 15:18:00,NaN,NaN
1,11000.0,1000.0,S28E19,8027,C6.8,NaN,360,878,True,False,1997-04-07 14:30:00,1997-04-07 17:30:00,1997-04-07 14:27:00,NaN,NaN
2,12000.0,80.0,N21W08,8038,C1.3,NaN,360,464,True,False,1997-05-12 05:15:00,1997-05-14 16:00:00,1997-05-12 05:30:00,NaN,NaN
3,5000.0,500.0,N05W12,8040,M1.3,263,165,296,False,False,1997-05-21 20:20:00,1997-05-21 22:00:00,1997-05-21 21:00:00,NaN,NaN
4,6000.0,2000.0,S29E25,8088,C1.4,133,155,712,False,False,1997-09-23 21:53:00,1997-09-23 22:16:00,1997-09-23 22:02:00,NaN,NaN
5,14000.0,250.0,S20W13,8100,C8.6,240,109,227,False,False,1997-11-03 05:15:00,1997-11-03 12:00:00,1997-11-03 05:28:00,NaN,NaN
6,14000.0,5000.0,S16W21,8100,M4.2,233,122,352,False,False,1997-11-03 10:30:00,1997-11-03 11:30:00,1997-11-03 11:11:00,NaN,NaN
7,14000.0,100.0,S14W33,8100,X2.1,NaN,360,785,True,False,1997-11-04 06:00:00,1997-11-05 04:30:00,1997-11-04 06:10:00,2.0,NaN
10,14000.0,8000.0,N25W52,8116,B9.4,278,73,191,False,False,1997-12-12 22:45:00,1997-12-12 23:20:00,1997-12-13 00:26:00,NaN,NaN
11,14000.0,10000.0,N21E25,8141,C1.1,NaN,360,693,True,False,1998-01-25 15:03:00,1998-01-25 15:18:00,1998-01-25 15:26:00,NaN,NaN
12,14000.0,7000.0,SW90,NaN,NaN,NaN,360,1397,True,False,1998-03-29 03:40:00,1998-03-29 03:52:00,1998-03-29 03:48:00,NaN,NaN
13,10000.0,35.0,S22W90,8194,M1.4,284,165,1863,False,False,1998-04-20 10:25:00,1998-04-22 06:00:00,1998-04-20 10:07:00,NaN,NaN
14,14000.0,200.0,S17E90,8210,X1.2,NaN,360,1691,True,False,1998-04-23 06:00:00,1998-04-23 15:30:00,1998-04-23 05:55:00,1.0,NaN
15,4700.0,2600.0,S20E90,8210,C8.9,100,84,1184,False,False,1998-04-24 09:17:00,1998-04-24 09:25:00,1998-04-24 08:55:00,NaN,NaN
16,10000.0,1000.0,S16E50,8210,X1.0,NaN,360,1385,True,False,1998-04-27 09:20:00,1998-04-27 10:00:00,1998-04-27 08:56:00,1.0,NaN
17,10000.0,2000.0,S18E20,8210,M6.8,NaN,360,1374,True,False,1998-04-29 16:30:00,1998-04-29 17:00:00,1998-04-29 16:58:00,NaN,NaN
18,5000.0,3000.0,S15W15,8210,X1.1,NaN,360,938,True,False,1998-05-02 14:25:00,1998-05-02 14:50:00,1998-05-02 14:06:00,1.0,NaN
20,9000.0,400.0,S14W89,8210,M7.7,262,178,2331,False,False,1998-05-09 03:35:00,1998-05-09 10:00:00,1998-05-09 03:35:00,NaN,NaN
21,10000.0,1000.0,N32W90,8214,B6.6,208,301,830,False,True,1998-05-11 21:40:00,1998-05-11 22:00:00,1998-05-11 21:55:00,NaN,NaN
22,14000.0,3000.0,N23W43,8222,B5.7,268,139,801,False,False,1998-05-19 10:00:00,1998-05-19 11:30:00,1998-05-19 10:27:00,NaN,NaN
23,4000.0,1000.0,N19W62,8226,C7.5,175,268,878,False,False,1998-05-27 13:30:00,1998-05-27 14:20:00,1998-05-27 13:45:00,NaN,NaN
24,8000.0,4000.0,N16E86,8243,M1.4,123,177,1223,False,False,1998-06-11 10:15:00,1998-06-11 10:20:00,1998-06-11 10:28:00,NaN,NaN
25,12000.0,50.0,S22W90,8232,M1.0,341,281,1484,False,False,1998-06-16 18:20:00,1998-06-17 21:00:00,1998-06-16 18:27:00,NaN,NaN
26,2600.0,1800.0,BACK,NaN,NaN,NaN,360,964,True,False,1998-06-20 19:39:00,1998-06-20 20:00:00,1998-06-20 18:20:00,NaN,NaN
27,6000.0,2000.0,N16W46,8243,C2.9,265,59,206,False,False,1998-06-22 07:15:00,1998-06-22 09:20:00,1998-06-22 05:01:00,NaN,NaN