# Data Science Project 1
Vasanth Rajasekaran and Sam Childs

## Collaboration Plan

### Step One

In [1]:
!pip install lxml

Requirement already satisfied: lxml in /opt/conda/lib/python3.8/site-packages (4.5.2)

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json 
import lxml
import re
url = 'https://www.spaceweatherlive.com/en/solar-activity/top-50-solar-flares'
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
response = requests.get(url, headers=headers)
content = response.content

ModuleNotFoundError: No module named 'lxml'

In [3]:
a = BeautifulSoup(content)
a.prettify()
solarTable = a.find('table')
table = pd.read_html(solarTable.prettify())
table=table[0]
table.columns = ['rank','x_class', 'date', 'region' ,'start_time', 'max_time', 'end_time', 'movie']
table

,rank,x_class,date,region,start_time,max_time,end_time,movie
0,1,X28+,2003/11/04,486,19:29,19:53,20:06,Movie View archive
1,2,X20+,2001/04/02,9393,21:32,21:51,22:03,Movie View archive
2,3,X17.2+,2003/10/28,486,09:51,11:10,11:24,Movie View archive
3,4,X17+,2005/09/07,808,17:17,17:40,18:03,Movie View archive
4,5,X14.4,2001/04/15,9415,13:19,13:50,13:55,Movie View archive
5,6,X10,2003/10/29,486,20:37,20:49,21:01,Movie View archive
6,7,X9.4,1997/11/06,8100,11:49,11:55,12:01,Movie View archive
7,8,X9.3,2017/09/06,2673,11:53,12:02,12:10,Movie View archive
8,9,X9,2006/12/05,930,10:18,10:35,10:45,Movie View archive
9,10,X8.3,2003/11/02,486,17:03,17:25,17:39,Movie View archive
10,11,X8.2,2017/09/10,2673,15:35,16:06,16:31,Movie View archive
11,12,X7.1,2005/01/20,720,06:36,07:01,07:26,Movie View archive
12,13,X6.9,2011/08/09,1263,07:48,08:05,08:08,Movie View archive
13,14,X6.5,2006/12/06,930,18:29,18:47,19:00,Movie View archive
14,15,X6.2,2005/09/09,808,19:13,20:04,20:36,Movie View archive
15,16,X6.2,2001/12/13,9733,14:20,14:30,14:35,Movie View archive
16,17,X5.7,2000/07/14,9077,10:03,10:24,10:43,Movie View archive
17,18,X5.6,2001/04/06,9415,19:10,19:21,19:31,Movie View archive
18,19,X5.4,2012/03/07,1429,00:02,00:24,00:40,Movie View archive
19,20,X5.4,2005/09/08,808,20:52,21:06,21:17,Movie View archive
20,21,X5.4,2003/10/23,486,08:19,08:35,08:49,Movie View archive
21,22,X5.3,2001/08/25,9591,16:23,16:45,17:04,Movie View archive
22,23,X4.9,2014/02/25,1990,00:39,00:49,01:03,Movie View archive
23,24,X4.9,1998/08/18,8307,22:10,22:19,22:28,View archive
24,25,X4.8,2002/07/23,39,00:18,00:35,00:47,Movie View archive
25,26,X4,2000/11/26,9236,16:34,16:48,16:56,Movie View archive
26,27,X3.9,2003/11/03,488,09:43,09:55,10:19,Movie View archive
27,28,X3.9,1998/08/19,8307,21:35,21:45,21:50,View archive
28,29,X3.8,2005/01/17,720,06:59,09:52,10:07,Movie View archive
29,30,X3.7,1998/11/22,8384,06:30,06:42,06:49,Movie View archive
30,31,X3.6,2005/09/09,808,09:42,09:59,10:08,Movie View archive
31,32,X3.6,2004/07/16,649,13:49,13:55,14:01,Movie View archive
32,33,X3.6,2003/05/28,365,00:17,00:27,00:39,Movie View archive
33,34,X3.4,2006/12/13,930,02:14,02:40,02:57,Movie View archive
34,35,X3.4,2001/12/28,9767,20:02,20:45,21:32,Movie View archive
35,36,X3.3,2013/11/05,1890,22:07,22:12,22:15,Movie View archive
36,37,X3.3,2002/07/20,39,21:04,21:30,21:54,Movie View archive
37,38,X3.3,1998/11/28,8395,04:54,05:52,06:13,Movie View archive
38,39,X3.2,2013/05/14,1748,00:00,01:11,01:20,Movie View archive
39,40,X3.1,2014/10/24,2192,21:07,21:41,22:13,Movie View archive
40,41,X3.1,2002/08/24,69,00:49,01:12,01:31,Movie View archive
41,42,X3,2002/07/15,30,19:59,20:08,20:14,Movie View archive
42,43,X2.8,2013/05/13,1748,15:48,16:05,16:16,Movie View archive
43,44,X2.8,2001/12/11,9733,07:58,08:08,08:14,Movie View archive
44,45,X2.8,1998/08/18,8307,08:14,08:24,08:32,View archive
45,46,X2.7,2015/05/05,2339,22:05,22:11,22:15,Movie View archive
46,47,X2.7,2003/11/03,488,01:09,01:30,01:45,Movie View archive
47,48,X2.7,1998/05/06,8210,07:58,08:09,08:20,Movie View archive
48,49,X2.6,2005/01/15,720,22:25,23:02,23:31,Movie View archive
49,50,X2.6,2001/09/24,9632,09:32,10:38,11:09,Movie View archive

In [ ]:
import datetime
del table['movie']

In [38]:
import re
import numpy as np
url2 = 'https://cdaw.gsfc.nasa.gov/CME_list/radio/waves_type2.html'
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
response2 = requests.get(url2, headers=headers)
content2 = response2.content

In [46]:
b = BeautifulSoup(content2, "html.parser")
s = str(b.pre).split('\n')[12:-2]
data = {"Start Date": [],
        "Start Time": [],
        "End Date": [],
        "End Time": [],
        "Max Frequency": [],
        "Min Frequency": [],
        "Flare Location": [],
        "NOAA": [],
        "Imp": [],
        "CME Date": [],
        "CME Time": [],
        "CPA": [],
        "Width": [],
        "Speed": []}
        
dfNasa = pd.DataFrame(data)

In [47]:
for i in s:
    row = i.split(' ')
    a = [x for x in row if x]
    b = [y for y in a if y!='<a']
    temp = re.sub(r'href[^<]+>', '', b[4])
    noLinkMax = re.sub(r'</a>','', temp)
    
    temp = re.sub(r'href[^<]+>', '', b[5])
    noLinkMin = re.sub(r'</a>','', temp)
    
    tempCME = re.sub(r'href[^<]+>', '', b[9])
    noLinkCME = re.sub(r'</a>','', tempCME)
    
    tempSpeed = re.sub(r'href[^<]+>', '', b[13])
    noLinkSpeed = re.sub(r'</a>','', tempSpeed)
    
    insertRow = pd.Series({"Start Date": b[0],
                       "Start Time": b[1],
                       "End Date": b[2],
                       "End Time": b[3],
                       "Max Frequency": noLinkMax,
                       "Min Frequency": noLinkMin,
                       "Flare Location": b[6],
                       "NOAA": b[7],
                       "Imp": b[8],
                       "CME Date": noLinkCME,
                       "CME Time": b[10],
                       "CPA": b[11],
                       "Width": b[12],
                       "Speed": noLinkSpeed
                      })
    dfNasa = dfNasa.append(insertRow, ignore_index=True)
dfNasa

,Start Date,Start Time,End Date,End Time,Max Frequency,Min Frequency,Flare Location,NOAA,Imp,CME Date,CME Time,CPA,Width,Speed
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,74,79,312
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,Halo,360,878
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,Halo,360,464
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,263,165,296
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,133,155,712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,2017/09/04,20:27,09/05,04:54,14000,210,S10W12,12673,M5.5,09/04,20:12,Halo,360,1418
514,2017/09/06,12:05,09/07,08:00,16000,70,S08W33,12673,X9.3,09/06,12:24,Halo,360,1571
515,2017/09/10,16:02,09/11,06:50,16000,150,S09W92,-----,X8.3,09/10,16:00,Halo,360,3163
516,2017/09/12,07:38,09/12,07:43,16000,13000,N08E48,12680,C3.0,09/12,08:03,124,96,252
517,2017/09/17,11:45,09/17,12:35,16000,900,S08E170,-----,----,09/17,12:00,Halo,360,1385

In [48]:
dfNasa["Flare Location"] = dfNasa["Flare Location"].replace("Back","BACK")
dfNasa["Flare Location"] = dfNasa["Flare Location"].replace("Back?","BACK")

dfNasa["NOAA"] = dfNasa["NOAA"].replace("-----",np.NaN)
dfNasa["NOAA"] = dfNasa["NOAA"].replace("DSF","FILA")
dfNasa["Imp"] = dfNasa["Imp"].replace("----",np.NaN)

dfNasa["CME Date"] = dfNasa["CME Date"].replace("----",np.NaN)
dfNasa["CME Date"] = dfNasa["CME Date"].replace("----",np.NaN)
dfNasa["CPA"] = dfNasa["CPA"].replace("----",np.NaN)
dfNasa["Is Halo"] = [True if row == "Halo" else False for row in dfNasa['CPA']]
dfNasa["CPA"] = dfNasa["CPA"].replace("Halo",np.NaN)
dfNasa["Width"] = dfNasa["Width"].replace("----",np.NaN)
dfNasa["Speed"] = dfNasa["Speed"].replace("----",np.NaN)
dfNasa["Width Lower Bound"] = [True if "&gt;" in str(row) else False for row in dfNasa['Width']]
dfNasa["Width"] = [int(str(row)[4:]) if "&gt;" in str(row) else row for row in dfNasa['Width']]
dfNasa["End Time"] = dfNasa["End Time"].replace("24:00","23:59")
dfNasa["Start DateTime"] = pd.to_datetime(dfNasa["Start Date"] + " " + dfNasa["Start Time"])
dfNasa["End DateTime"] = pd.to_datetime(dfNasa["Start Date"] + " " + dfNasa["End Time"])
#dfNasa["CME DateTime"] = pd.to_datetime(dfNasa["Start Date"] + " " + dfNasa["CME Time"])
# Waiting for the CME REGEX to work properly

# Reorder table
"""
dfNasa = dfNasa[['Start DateTime', 'End DateTime',
                "Max Frequency", "Min Frequency",
                "Flare Location", "NOAA","Imp",
                "CME DateTime", "CPA", "Width",
                "Speed","Is Halo","Width Lower Bound"]] 
"""


dfNasa = dfNasa.drop(["Start Date", "Start Time", "End Date", "End Time", "CME Date", "CME Time"], axis = 1)
# And don't forget to check each column for the correct datatype
dfNasa

,Max Frequency,Min Frequency,Flare Location,NOAA,Imp,CPA,Width,Speed,Is Halo,Width Lower Bound,Start DateTime,End DateTime
0,8000,4000,S25E16,8026,M1.3,74,79,312,False,False,1997-04-01 14:00:00,1997-04-01 14:15:00
1,11000,1000,S28E19,8027,C6.8,NaN,360,878,True,False,1997-04-07 14:30:00,1997-04-07 17:30:00
2,12000,80,N21W08,8038,C1.3,NaN,360,464,True,False,1997-05-12 05:15:00,1997-05-12 16:00:00
3,5000,500,N05W12,8040,M1.3,263,165,296,False,False,1997-05-21 20:20:00,1997-05-21 22:00:00
4,6000,2000,S29E25,8088,C1.4,133,155,712,False,False,1997-09-23 21:53:00,1997-09-23 22:16:00
...,...,...,...,...,...,...,...,...,...,...,...,...
513,14000,210,S10W12,12673,M5.5,NaN,360,1418,True,False,2017-09-04 20:27:00,2017-09-04 04:54:00
514,16000,70,S08W33,12673,X9.3,NaN,360,1571,True,False,2017-09-06 12:05:00,2017-09-06 08:00:00
515,16000,150,S09W92,NaN,X8.3,NaN,360,3163,True,False,2017-09-10 16:02:00,2017-09-10 06:50:00
516,16000,13000,N08E48,12680,C3.0,124,96,252,False,False,2017-09-12 07:38:00,2017-09-12 07:43:00
517,16000,900,S08E170,NaN,NaN,NaN,360,1385,True,False,2017-09-17 11:45:00,2017-09-17 12:35:00

In [ ]:
rowList = []
for row in range(0,len(dataLines)):
    #dLCuts = dataLines[row].split(" ")
    # Regex + Int(): 6, 9, 29
    # Regex: 19,
    # Int: 
    # N/A + Int(): 14
    insertRow = pd.Series({"Start Date": dLCuts[0],
                          "Start Time": dLCuts[1],
                           "End Date": dLCuts[2],
                           "End Time": dLCuts[3],
                           "Max Frequency": dLCuts[6],
                           "Min Frequency": dLCuts[9],
                           "Location": dLCuts[12],
                           "NOAA": dLCuts[14],
                           "Imp": dLCuts[15],
                           "CME Date": dLCuts[19],
                           "CME Time": dLCuts[20],
                           "CPA": dLCuts[23],
                           "Width": dLCuts[26],
                           "Speed": dLCuts[29]
                          })
    rowList.append(insertRow)
df = pd.DataFrame(rowList)
df.head()